---

- hosts: dev
  tasks:
    - name: Get the token
      uri:
        return_content: yes
        url: "{{ coreos_discovery_url }}{{ coreos_cluster_size | default(3) }}"
      register: coreoes_discovery_response

    - name: Set the discovery token
      set_fact:
        coreoes_discovery_token: "{{ coreoes_discovery_response.content }}"

    - name: Make the vagrant folder
      file:
        path: "{{ coreos_vagrant_dir }}"
        state: directory

    - name: Copy the user-data template into the new directory
      template:
        dest: "{{ coreos_vagrant_dir }}/{{ cloud_config_file }}"
        src: templates/user-data.j2

    - name: Copy the config template into the new directory
      template:
        dest: "{{ coreos_vagrant_dir }}/{{ vagrant_config_file }}"
        src: templates/config.rb.j2

    - name: Copy the Vagrantfile into the new directory
      template:
        dest: "{{ coreos_vagrant_dir }}/{{ vagrant_vagrantfile }}"
        src: templates/Vagrantfile.j2

- hosts: coreos
  gather_facts: no
  roles:
    - defunctzombie.coreos-bootstrap
...
